// AUTO-GENERATED from public/amber/*.xlsx + photo folders — Amber Glass vendor catalog seed.
// Regenerate with: node scripts/gen-amber-seed.mjs
import type { Product } from './products';

export const AMBER_PRODUCTS: Product[] = [
  {
    "id": "sup-amber:G100",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "G100",
    "name": "Amber Glass G100",
    "collection": "Amber Glass Line",
    "category": "Stemware",
    "priceUsd": 13.14,
    "stockIntl": 10,
    "cartonType": "x1 pcs in luxury box",
    "pcsPerCarton": 1,
    "imageKey": "/images/amber/G100-1.jpeg",
    "images": [
      "/images/amber/G100-1.jpeg",
      "/images/amber/G100-G101-1.jpg",
      "/images/amber/G100-2.jpg",
      "/images/amber/G100-3.jpg",
      "/images/amber/G100-4.jpg",
      "/images/amber/G100-5.png"
    ],
    "priceEur": 12.09
  },
  {
    "id": "sup-amber:G101",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "G101",
    "name": "Amber Glass G101",
    "collection": "Amber Glass Line",
    "category": "Stemware",
    "priceUsd": 13.14,
    "stockIntl": 200,
    "cartonType": "x1 pcs in luxury box",
    "pcsPerCarton": 1,
    "imageKey": "/images/amber/G101-1.jpg",
    "images": [
      "/images/amber/G101-1.jpg",
      "/images/amber/G100-G101-1.jpg",
      "/images/amber/G101-2.jpg",
      "/images/amber/G101-3.jpg"
    ],
    "priceEur": 12.09
  },
  {
    "id": "sup-amber:G102",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "G102",
    "name": "Amber Glass G102",
    "collection": "Amber Glass Line",
    "category": "Stemware",
    "priceUsd": 14.94,
    "stockIntl": 60,
    "cartonType": "x1 pcs in luxury box",
    "pcsPerCarton": 1,
    "imageKey": "/images/amber/G102-1.jpeg",
    "images": [
      "/images/amber/G102-1.jpeg",
      "/images/amber/G102-G202-1.jpg",
      "/images/amber/G102-2.jpeg",
      "/images/amber/G102-3.jpeg",
      "/images/amber/G102-4.jpg",
      "/images/amber/G102-6.jpg",
      "/images/amber/G102-7.jpg",
      "/images/amber/G102-8.png"
    ],
    "priceEur": 13.74
  },
  {
    "id": "sup-amber:G110",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "G110",
    "name": "Amber Glass G110",
    "collection": "Amber Glass Line",
    "category": "Stemware",
    "priceUsd": 12.06,
    "stockIntl": 300,
    "cartonType": "x1 pcs in luxury box",
    "pcsPerCarton": 1,
    "imageKey": "/images/amber/G110-1.jpg",
    "images": [
      "/images/amber/G110-1.jpg",
      "/images/amber/G110-2.jpg",
      "/images/amber/G110-3.jpg",
      "/images/amber/G110-4.jpg",
      "/images/amber/G110-5.png"
    ],
    "priceEur": 11.1
  },
  {
    "id": "sup-amber:G111",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "G111",
    "name": "Amber Glass G111",
    "collection": "Amber Glass Line",
    "category": "Stemware",
    "priceUsd": 12.06,
    "stockIntl": 400,
    "cartonType": "x1 pcs in luxury box",
    "pcsPerCarton": 1,
    "imageKey": "/images/amber/G111-1.jpg",
    "images": [
      "/images/amber/G111-1.jpg",
      "/images/amber/G111-2.jpg",
      "/images/amber/G111-3.jpg"
    ],
    "priceEur": 11.1
  },
  {
    "id": "sup-amber:G120",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "G120",
    "name": "Amber Glass G120",
    "collection": "Amber Glass Line",
    "category": "Stemware",
    "priceUsd": 12.06,
    "stockIntl": 300,
    "cartonType": "x1 pcs in luxury box",
    "pcsPerCarton": 1,
    "imageKey": "/images/amber/G120-1.jpg",
    "images": [
      "/images/amber/G120-1.jpg",
      "/images/amber/G120-2.jpg",
      "/images/amber/G120-3.jpg"
    ],
    "priceEur": 11.1
  },
  {
    "id": "sup-amber:G200",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "G200",
    "name": "Amber Glass G200",
    "collection": "Amber Glass Line",
    "category": "Stemware",
    "priceUsd": 13.14,
    "stockIntl": 300,
    "cartonType": "x1 pcs in luxury box",
    "pcsPerCarton": 1,
    "imageKey": "/images/amber/G200-1.jpg",
    "images": [
      "/images/amber/G200-1.jpg",
      "/images/amber/G200-G201-1.jpg",
      "/images/amber/G200-2.jpg",
      "/images/amber/G200-3.jpg",
      "/images/amber/G200-4.jpg",
      "/images/amber/G200-5.png"
    ],
    "priceEur": 12.09
  },
  {
    "id": "sup-amber:G201",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "G201",
    "name": "Amber Glass G201",
    "collection": "Amber Glass Line",
    "category": "Stemware",
    "priceUsd": 13.14,
    "stockIntl": 200,
    "cartonType": "x1 pcs in luxury box",
    "pcsPerCarton": 1,
    "imageKey": "/images/amber/G201-1.jpg",
    "images": [
      "/images/amber/G201-1.jpg",
      "/images/amber/G200-G201-1.jpg",
      "/images/amber/G201-2.jpg",
      "/images/amber/G201-3.jpg"
    ],
    "priceEur": 12.09
  },
  {
    "id": "sup-amber:G202",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "G202",
    "name": "Amber Glass G202",
    "collection": "Amber Glass Line",
    "category": "Stemware",
    "priceUsd": 14.94,
    "stockIntl": 0,
    "cartonType": "x1 pcs in luxury box",
    "pcsPerCarton": 1,
    "imageKey": "/images/amber/G202-1.jpg",
    "images": [
      "/images/amber/G202-1.jpg",
      "/images/amber/G102-G202-1.jpg",
      "/images/amber/G202-2.jpg",
      "/images/amber/G202-3.jpg",
      "/images/amber/G202-4.jpg",
      "/images/amber/G202-6.jpg",
      "/images/amber/G202-7.png"
    ],
    "priceEur": 13.74
  },
  {
    "id": "sup-amber:G300",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "G300",
    "name": "Amber Glass G300",
    "collection": "Amber Glass Line",
    "category": "Stemware",
    "priceUsd": 10.44,
    "stockIntl": 400,
    "cartonType": "x1 pcs in luxury box",
    "pcsPerCarton": 1,
    "imageKey": "/images/amber/G300-1.jpg",
    "images": [
      "/images/amber/G300-1.jpg",
      "/images/amber/G300-G410-1.jpg",
      "/images/amber/G300-2.jpg",
      "/images/amber/G300-3.jpg",
      "/images/amber/G300-4.png"
    ],
    "priceEur": 9.6
  },
  {
    "id": "sup-amber:G301",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "G301",
    "name": "Amber Glass G301",
    "collection": "Amber Glass Line",
    "category": "Stemware",
    "priceUsd": 10.44,
    "stockIntl": 100,
    "cartonType": "x1 pcs in luxury box",
    "pcsPerCarton": 1,
    "imageKey": "/images/amber/G301-1.jpg",
    "images": [
      "/images/amber/G301-1.jpg",
      "/images/amber/G301-2.jpg",
      "/images/amber/G301-3.jpg"
    ],
    "priceEur": 9.6
  },
  {
    "id": "sup-amber:G410",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "G410",
    "name": "Amber Glass G410",
    "collection": "Amber Glass Line",
    "category": "Stemware",
    "priceUsd": 12.06,
    "stockIntl": 400,
    "cartonType": "x1 pcs in luxury box",
    "pcsPerCarton": 1,
    "imageKey": "/images/amber/G410-1.jpg",
    "images": [
      "/images/amber/G410-1.jpg",
      "/images/amber/G300-G410-1.jpg",
      "/images/amber/G410-2.jpg",
      "/images/amber/G410-3.jpeg",
      "/images/amber/G410-4.png"
    ],
    "priceEur": 11.1
  },
  {
    "id": "sup-amber:G411",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "G411",
    "name": "Amber Glass G411",
    "collection": "Amber Glass Line",
    "category": "Stemware",
    "priceUsd": 12.06,
    "stockIntl": 100,
    "cartonType": "x1 pcs in luxury box",
    "pcsPerCarton": 1,
    "imageKey": "/images/amber/G411-1.jpg",
    "images": [
      "/images/amber/G411-1.jpg",
      "/images/amber/G411-2.jpg",
      "/images/amber/G411-3.jpg"
    ],
    "priceEur": 11.1
  },
  {
    "id": "sup-amber:G500",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "G500",
    "name": "Amber Glass G500",
    "collection": "Amber Glass Line",
    "category": "Stemware",
    "priceUsd": 14.16,
    "stockIntl": 500,
    "cartonType": "x1 pcs in luxury box",
    "pcsPerCarton": 1,
    "imageKey": "/images/amber/G500-1.jpg",
    "images": [
      "/images/amber/G500-1.jpg",
      "/images/amber/G500-G501-1.jpg",
      "/images/amber/G500-2.jpg",
      "/images/amber/G500-3.jpg",
      "/images/amber/G500-4.jpg",
      "/images/amber/G500-5.jpg",
      "/images/amber/G500-6.png"
    ],
    "priceEur": 13.03
  },
  {
    "id": "sup-amber:G501",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "G501",
    "name": "Amber Glass G501",
    "collection": "Amber Glass Line",
    "category": "Stemware",
    "priceUsd": 14.16,
    "stockIntl": 300,
    "cartonType": "x1pcs in luxury box",
    "pcsPerCarton": 1,
    "imageKey": "/images/amber/G501-1.jpg",
    "images": [
      "/images/amber/G501-1.jpg",
      "/images/amber/G500-G501-1.jpg",
      "/images/amber/G501-2.jpg",
      "/images/amber/G501-3.jpg",
      "/images/amber/G501-4.png"
    ],
    "priceEur": 13.03
  },
  {
    "id": "sup-amber:G502",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "G502",
    "name": "Amber Glass G502",
    "collection": "Amber Glass Line",
    "category": "Stemware",
    "priceUsd": 14.94,
    "stockIntl": 100,
    "cartonType": "x1 pcs in luxury box",
    "pcsPerCarton": 1,
    "imageKey": "/images/amber/G502-1.jpg",
    "images": [
      "/images/amber/G502-1.jpg",
      "/images/amber/G502-2.jpg",
      "/images/amber/G502-3.jpg",
      "/images/amber/G502-4.jpg",
      "/images/amber/G502-5.jpg",
      "/images/amber/G502-6.jpg",
      "/images/amber/G502-7.jpg",
      "/images/amber/G502-8.jpg"
    ],
    "priceEur": 13.74
  },
  {
    "id": "sup-amber:G510",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "G510",
    "name": "Amber Glass G510",
    "collection": "Amber Glass Line",
    "category": "Stemware",
    "priceUsd": 14.16,
    "stockIntl": 400,
    "cartonType": "x1 pcs in luxury box",
    "pcsPerCarton": 1,
    "imageKey": "/images/amber/G510-1.jpg",
    "images": [
      "/images/amber/G510-1.jpg",
      "/images/amber/G510-2.jpg",
      "/images/amber/G510-3.jpg",
      "/images/amber/G510-4.jpg"
    ],
    "priceEur": 13.03
  },
  {
    "id": "sup-amber:G600",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "G600",
    "name": "Amber Glass G600",
    "collection": "Amber Glass Line",
    "category": "Stemware",
    "priceUsd": 13.14,
    "stockIntl": 250,
    "cartonType": "x1 pcs in luxury box",
    "pcsPerCarton": 1,
    "imageKey": "/images/amber/G600-1.jpg",
    "images": [
      "/images/amber/G600-1.jpg",
      "/images/amber/G600-2.jpg",
      "/images/amber/G600-3.jpg"
    ],
    "priceEur": 12.09
  },
  {
    "id": "sup-amber:G601",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "G601",
    "name": "Amber Glass G601",
    "collection": "Amber Glass Line",
    "category": "Stemware",
    "priceUsd": 11.34,
    "stockIntl": 12,
    "cartonType": "x1 pcs in luxury box",
    "pcsPerCarton": 1,
    "imageKey": "/images/amber/G601-1.jpg",
    "images": [
      "/images/amber/G601-1.jpg",
      "/images/amber/G601-2.jpg"
    ],
    "priceEur": 10.43
  },
  {
    "id": "sup-amber:G602",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "G602",
    "name": "Amber Glass G602",
    "collection": "Amber Glass Line",
    "category": "Stemware",
    "priceUsd": 14.94,
    "stockIntl": 20,
    "cartonType": "x1 pcs in luxury box",
    "pcsPerCarton": 1,
    "imageKey": "/images/amber/G602-1.jpg",
    "images": [
      "/images/amber/G602-1.jpg",
      "/images/amber/G602-2.jpg",
      "/images/amber/G602-3.jpg",
      "/images/amber/G602-4.jpg",
      "/images/amber/G602-5.jpg"
    ],
    "priceEur": 13.74
  },
  {
    "id": "sup-amber:G610",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "G610",
    "name": "Amber Glass G610",
    "collection": "Amber Glass Line",
    "category": "Stemware",
    "priceUsd": 13.14,
    "stockIntl": 300,
    "cartonType": "x1 pcs in luxury box",
    "pcsPerCarton": 1,
    "imageKey": "/images/amber/G610-1.jpg",
    "images": [
      "/images/amber/G610-1.jpg",
      "/images/amber/G610-2.jpg",
      "/images/amber/G610-3.jpg",
      "/images/amber/G610-4.jpg"
    ],
    "priceEur": 12.09
  },
  {
    "id": "sup-amber:V100 (6 pcs inside)",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "V100 (6 pcs inside)",
    "name": "Amber Glass V100 (6 pcs inside)",
    "collection": "Amber Glass Line",
    "category": "Vases",
    "priceUsd": 30,
    "stockIntl": 50,
    "cartonType": "x6 pcs in carton box",
    "pcsPerCarton": 6,
    "imageKey": "/images/amber/V100-1.jpg",
    "images": [
      "/images/amber/V100-1.jpg",
      "/images/amber/V100-V101-1.jpg",
      "/images/amber/V100-2.jpg",
      "/images/amber/V100-3.jpg"
    ],
    "priceEur": 27.6
  },
  {
    "id": "sup-amber:V101 (6 pcs inside)",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "V101 (6 pcs inside)",
    "name": "Amber Glass V101 (6 pcs inside)",
    "collection": "Amber Glass Line",
    "category": "Vases",
    "priceUsd": 30,
    "stockIntl": 0,
    "cartonType": "x6 pcs in carton box",
    "pcsPerCarton": 6,
    "imageKey": "/images/amber/V101-1.jpg",
    "images": [
      "/images/amber/V101-1.jpg",
      "/images/amber/V100-V101-1.jpg",
      "/images/amber/V101-2.jpg",
      "/images/amber/V101-3.jpg"
    ],
    "priceEur": 27.6
  },
  {
    "id": "sup-amber:V102 (6 pcs inside)",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "V102 (6 pcs inside)",
    "name": "Amber Glass V102 (6 pcs inside)",
    "collection": "Amber Glass Line",
    "category": "Vases",
    "priceUsd": 30,
    "stockIntl": 0,
    "cartonType": "x6 pcs in carton box",
    "pcsPerCarton": 6,
    "imageKey": "/images/amber/V102-1.jpg",
    "images": [
      "/images/amber/V102-1.jpg",
      "/images/amber/V102-2.jpg",
      "/images/amber/V102-3.jpg",
      "/images/amber/V102-4.jpg",
      "/images/amber/V102-5.jpg",
      "/images/amber/V102-6.jpg"
    ],
    "priceEur": 27.6
  },
  {
    "id": "sup-amber:CG100 (2 pcs inside)",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "CG100 (2 pcs inside)",
    "name": "Amber Glass CG100 (2 pcs inside)",
    "collection": "Amber Glass Line",
    "category": "Stemware",
    "priceUsd": 30,
    "stockIntl": 150,
    "cartonType": "x2 pcs in carton box",
    "pcsPerCarton": 2,
    "imageKey": "/images/amber/CG100-1.jpg",
    "images": [
      "/images/amber/CG100-1.jpg",
      "/images/amber/CG100-2.jpg",
      "/images/amber/CG100-3.jpg",
      "/images/amber/CG100-4.jpg",
      "/images/amber/CG100-5.jpg",
      "/images/amber/CG100-6.jpg",
      "/images/amber/CG100-7.jpg",
      "/images/amber/CG100-8.jpg"
    ],
    "priceEur": 27.6
  },
  {
    "id": "sup-amber:CG200 (2 pcs inside)",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "CG200 (2 pcs inside)",
    "name": "Amber Glass CG200 (2 pcs inside)",
    "collection": "Amber Glass Line",
    "category": "Stemware",
    "priceUsd": 30,
    "stockIntl": 150,
    "cartonType": "x2 pcs in carton box",
    "pcsPerCarton": 2,
    "imageKey": "/images/amber/CG200-1.jpg",
    "images": [
      "/images/amber/CG200-1.jpg",
      "/images/amber/CG200-2.jpg",
      "/images/amber/CG200-3.jpg"
    ],
    "priceEur": 27.6
  },
  {
    "id": "sup-amber:CG300 (2 pcs inside)",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "CG300 (2 pcs inside)",
    "name": "Amber Glass CG300 (2 pcs inside)",
    "collection": "Amber Glass Line",
    "category": "Stemware",
    "priceUsd": 27,
    "stockIntl": 200,
    "cartonType": "x2 pcs in carton box",
    "pcsPerCarton": 2,
    "imageKey": "/images/amber/CG300-1.jpg",
    "images": [
      "/images/amber/CG300-1.jpg",
      "/images/amber/CG300-2.jpg",
      "/images/amber/CG300-3.jpg"
    ],
    "priceEur": 24.84
  },
  {
    "id": "sup-amber:Amber Set",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Amber Set",
    "name": "Amber Glass Amber Set",
    "collection": "Amber Glass Line",
    "category": "Gift Sets",
    "priceUsd": 30,
    "stockIntl": 250,
    "cartonType": "x6 pcs in carton box",
    "pcsPerCarton": 6,
    "imageKey": "/images/amber/Amber-Set-1.jpg",
    "images": [
      "/images/amber/Amber-Set-1.jpg",
      "/images/amber/Amber-Set-2.jpg",
      "/images/amber/Amber-Set-3.jpg",
      "/images/amber/Amber-Set-4.jpg"
    ],
    "priceEur": 27.6
  },
  {
    "id": "sup-amber:Amber Box (2 pcs inside)",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Amber Box (2 pcs inside)",
    "name": "Amber Glass Amber Box (2 pcs inside)",
    "collection": "Amber Glass Line",
    "category": "Gift Sets",
    "priceUsd": 21,
    "stockIntl": 250,
    "cartonType": "x2 pcs in carton box",
    "pcsPerCarton": 2,
    "imageKey": "/images/amber/Amber-Box-1.jpg",
    "images": [
      "/images/amber/Amber-Box-1.jpg",
      "/images/amber/Amber-Box-2.jpg",
      "/images/amber/Amber-Box-3.jpg",
      "/images/amber/Amber-Box-4.png"
    ],
    "priceEur": 19.32
  },
  {
    "id": "sup-amber:Amber Box II (2 pcs inside)",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Amber Box II (2 pcs inside)",
    "name": "Amber Glass Amber Box II (2 pcs inside)",
    "collection": "Amber Glass Line",
    "category": "Gift Sets",
    "priceUsd": 21,
    "stockIntl": 40,
    "cartonType": "x2 pcs in carton box",
    "pcsPerCarton": 2,
    "imageKey": "/images/amber/Amber-Box-II-1.jpg",
    "images": [
      "/images/amber/Amber-Box-II-1.jpg",
      "/images/amber/Amber-Box-II-black-1.jpg",
      "/images/amber/Amber-Box-II-black-1-1.jpg",
      "/images/amber/Amber-Box-II-black-2-1.jpg",
      "/images/amber/Amber-Box-II-black-3-1.jpg",
      "/images/amber/Amber-Box-II-2.jpg",
      "/images/amber/Amber-Box-II-black-2.jpg",
      "/images/amber/Amber-Box-II-3.jpg",
      "/images/amber/Amber-Box-II-black-3.jpg",
      "/images/amber/Amber-Box-II-4.jpg",
      "/images/amber/Amber-Box-II-5.jpg"
    ],
    "priceEur": 19.32
  },
  {
    "id": "sup-amber:Crystal Box (2 pcs inside) - pattern no 1",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Crystal Box (2 pcs inside) - pattern no 1",
    "name": "Amber Glass Crystal Box (2 pcs inside) - pattern no 1",
    "collection": "Amber Glass Line",
    "category": "Gift Sets",
    "priceUsd": 34.2,
    "stockIntl": 40,
    "cartonType": "x2 pcs in carton box",
    "pcsPerCarton": 2,
    "imageKey": "/images/amber/Crystal-Box-1.jpg",
    "images": [
      "/images/amber/Crystal-Box-1.jpg",
      "/images/amber/Crystal-Box-2.jpg"
    ],
    "priceEur": 31.46
  },
  {
    "id": "sup-amber:Crystal Box (2 pcs inside) - pattern no 2",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Crystal Box (2 pcs inside) - pattern no 2",
    "name": "Amber Glass Crystal Box (2 pcs inside) - pattern no 2",
    "collection": "Amber Glass Line",
    "category": "Gift Sets",
    "priceUsd": 34.2,
    "stockIntl": 40,
    "cartonType": "x2 pcs in carton box",
    "pcsPerCarton": 2,
    "imageKey": "/images/amber/Crystal-Box-1.jpg",
    "images": [
      "/images/amber/Crystal-Box-1.jpg",
      "/images/amber/Crystal-Box-2.jpg"
    ],
    "priceEur": 31.46
  },
  {
    "id": "sup-amber:Crystal Box (2 pcs inside) - pattern no 3",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Crystal Box (2 pcs inside) - pattern no 3",
    "name": "Amber Glass Crystal Box (2 pcs inside) - pattern no 3",
    "collection": "Amber Glass Line",
    "category": "Gift Sets",
    "priceUsd": 34.2,
    "stockIntl": 40,
    "cartonType": "x2 pcs in carton box",
    "pcsPerCarton": 2,
    "imageKey": "/images/amber/Crystal-Box-1.jpg",
    "images": [
      "/images/amber/Crystal-Box-1.jpg",
      "/images/amber/Crystal-Box-2.jpg"
    ],
    "priceEur": 31.46
  },
  {
    "id": "sup-amber:Crystal Box (2 pcs inside) - pattern no 4",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Crystal Box (2 pcs inside) - pattern no 4",
    "name": "Amber Glass Crystal Box (2 pcs inside) - pattern no 4",
    "collection": "Amber Glass Line",
    "category": "Gift Sets",
    "priceUsd": 34.2,
    "stockIntl": 40,
    "cartonType": "x2 pcs in carton box",
    "pcsPerCarton": 2,
    "imageKey": "/images/amber/Crystal-Box-1.jpg",
    "images": [
      "/images/amber/Crystal-Box-1.jpg",
      "/images/amber/Crystal-Box-2.jpg"
    ],
    "priceEur": 31.46
  },
  {
    "id": "sup-amber:Crystal Box (2 pcs inside) - pattern no 5",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Crystal Box (2 pcs inside) - pattern no 5",
    "name": "Amber Glass Crystal Box (2 pcs inside) - pattern no 5",
    "collection": "Amber Glass Line",
    "category": "Gift Sets",
    "priceUsd": 34.2,
    "stockIntl": 0,
    "cartonType": "x2 pcs in carton box",
    "pcsPerCarton": 2,
    "imageKey": "/images/amber/Crystal-Box-1.jpg",
    "images": [
      "/images/amber/Crystal-Box-1.jpg",
      "/images/amber/Crystal-Box-2.jpg"
    ],
    "priceEur": 31.46
  },
  {
    "id": "sup-amber:Crystal Box (2 pcs inside) - pattern no 6",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Crystal Box (2 pcs inside) - pattern no 6",
    "name": "Amber Glass Crystal Box (2 pcs inside) - pattern no 6",
    "collection": "Amber Glass Line",
    "category": "Gift Sets",
    "priceUsd": 34.2,
    "stockIntl": 0,
    "cartonType": "x2 pcs in carton box",
    "pcsPerCarton": 2,
    "imageKey": "/images/amber/Crystal-Box-1.jpg",
    "images": [
      "/images/amber/Crystal-Box-1.jpg",
      "/images/amber/Crystal-Box-2.jpg"
    ],
    "priceEur": 31.46
  },
  {
    "id": "sup-amber:Crystal Box (2 pcs inside) - pattern no 7",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Crystal Box (2 pcs inside) - pattern no 7",
    "name": "Amber Glass Crystal Box (2 pcs inside) - pattern no 7",
    "collection": "Amber Glass Line",
    "category": "Gift Sets",
    "priceUsd": 34.2,
    "stockIntl": 0,
    "cartonType": "x2 pcs in carton box",
    "pcsPerCarton": 2,
    "imageKey": "/images/amber/Crystal-Box-1.jpg",
    "images": [
      "/images/amber/Crystal-Box-1.jpg",
      "/images/amber/Crystal-Box-2.jpg"
    ],
    "priceEur": 31.46
  },
  {
    "id": "sup-amber:Crystal Box (2 pcs inside) - pattern no 8",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Crystal Box (2 pcs inside) - pattern no 8",
    "name": "Amber Glass Crystal Box (2 pcs inside) - pattern no 8",
    "collection": "Amber Glass Line",
    "category": "Gift Sets",
    "priceUsd": 34.2,
    "stockIntl": 40,
    "cartonType": "x2 pcs in carton box",
    "pcsPerCarton": 2,
    "imageKey": "/images/amber/Crystal-Box-1.jpg",
    "images": [
      "/images/amber/Crystal-Box-1.jpg",
      "/images/amber/Crystal-Box-2.jpg"
    ],
    "priceEur": 31.46
  },
  {
    "id": "sup-amber:Amber Box III (2 pcs inside)",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Amber Box III (2 pcs inside)",
    "name": "Amber Glass Amber Box III (2 pcs inside)",
    "collection": "Amber Glass Line",
    "category": "Gift Sets",
    "priceUsd": 21,
    "stockIntl": 40,
    "cartonType": "x2 pcs in carton box",
    "pcsPerCarton": 2,
    "imageKey": "/images/amber/Amber-Box-III-1.jpg",
    "images": [
      "/images/amber/Amber-Box-III-1.jpg",
      "/images/amber/Amber-Box-III-2.jpg",
      "/images/amber/Amber-Box-III-3.jpg"
    ],
    "priceEur": 19.32
  },
  {
    "id": "sup-amber:Model 19-2276A",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Model 19-2276A",
    "name": "Wine glass with optic touch effect",
    "collection": "Amber Glass Lines",
    "category": "Stemware",
    "productionType": "Wine glass with optic touch effect",
    "priceUsd": 5.3,
    "stockIntl": 1200,
    "cartonType": "x6 pcs in carton box",
    "pcsPerCarton": 6,
    "priceEur": 4.88
  },
  {
    "id": "sup-amber:Model 19-2670",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Model 19-2670",
    "name": "Standard shape wine glass",
    "collection": "Amber Glass Lines",
    "category": "Stemware",
    "productionType": "Standard shape wine glass",
    "priceUsd": 4.2,
    "stockIntl": 1500,
    "cartonType": "x6 pcs in carton box",
    "pcsPerCarton": 6,
    "priceEur": 3.86
  },
  {
    "id": "sup-amber:Model 19-2350",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Model 19-2350",
    "name": "Sparkling glass with optic touch effect",
    "collection": "Amber Glass Lines",
    "category": "Stemware",
    "productionType": "Sparkling glass with optic touch effect",
    "priceUsd": 4.75,
    "stockIntl": 2600,
    "cartonType": "x6 pcs in carton box",
    "pcsPerCarton": 6,
    "priceEur": 4.37
  },
  {
    "id": "sup-amber:Model 19-3104C",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Model 19-3104C",
    "name": "Sparkling glass with optic touch effect",
    "collection": "Amber Glass Lines",
    "category": "Stemware",
    "productionType": "Sparkling glass with optic touch effect",
    "priceUsd": 4.75,
    "stockIntl": 402,
    "cartonType": "x6 pcs in carton box",
    "pcsPerCarton": 6,
    "priceEur": 4.37
  },
  {
    "id": "sup-amber:Model 19-2872",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Model 19-2872",
    "name": "Sparkling glass",
    "collection": "Amber Glass Lines",
    "category": "Stemware",
    "productionType": "Sparkling glass",
    "priceUsd": 4.2,
    "stockIntl": 1600,
    "cartonType": "x6 pcs in carton box",
    "pcsPerCarton": 6,
    "priceEur": 3.86
  },
  {
    "id": "sup-amber:Model 19-3223",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Model 19-3223",
    "name": "Cocktail glass with optic touch effect",
    "collection": "Amber Glass Lines",
    "category": "Barware",
    "productionType": "Cocktail glass with optic touch effect",
    "priceUsd": 4.75,
    "stockIntl": 324,
    "cartonType": "x6 pcs in carton box",
    "pcsPerCarton": 6,
    "priceEur": 4.37
  },
  {
    "id": "sup-amber:Model 19-3254",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Model 19-3254",
    "name": "Cocktail glass",
    "collection": "Amber Glass Lines",
    "category": "Barware",
    "productionType": "Cocktail glass",
    "priceUsd": 4.2,
    "stockIntl": 900,
    "cartonType": "x6 pcs in carton box",
    "pcsPerCarton": 6,
    "priceEur": 3.86
  },
  {
    "id": "sup-amber:Model 19-3388",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Model 19-3388",
    "name": "Cocktail glass",
    "collection": "Amber Glass Lines",
    "category": "Barware",
    "productionType": "Cocktail glass",
    "priceUsd": 4.2,
    "stockIntl": 500,
    "cartonType": "x6 pcs in carton box",
    "pcsPerCarton": 6,
    "priceEur": 3.86
  },
  {
    "id": "sup-amber:Model 19-2338",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Model 19-2338",
    "name": "Shot glass",
    "collection": "Amber Glass Lines",
    "category": "Barware",
    "productionType": "Shot glass",
    "priceUsd": 3.35,
    "stockIntl": 900,
    "cartonType": "x6 pcs in carton box",
    "pcsPerCarton": 6,
    "priceEur": 3.08
  },
  {
    "id": "sup-amber:Model 19-3297",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Model 19-3297",
    "name": "Shot glass",
    "collection": "Amber Glass Lines",
    "category": "Barware",
    "productionType": "Shot glass",
    "priceUsd": 3.35,
    "stockIntl": 432,
    "cartonType": "x6 pcs in carton box",
    "pcsPerCarton": 6,
    "priceEur": 3.08
  },
  {
    "id": "sup-amber:Model 20-1037",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Model 20-1037",
    "name": "Tumbler whisky glass with line pattern design",
    "collection": "Amber Glass Lines",
    "category": "Barware",
    "productionType": "Tumbler whisky glass with line pattern design",
    "priceUsd": 10.1,
    "stockIntl": 2000,
    "cartonType": "x6 pcs in carton box",
    "pcsPerCarton": 6,
    "priceEur": 9.29
  },
  {
    "id": "sup-amber:Model 23-281A",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Model 23-281A",
    "name": "Standard shape beer glass",
    "collection": "Amber Glass Lines",
    "category": "Tumblers & Highballs",
    "productionType": "Standard shape beer glass",
    "priceUsd": 5.3,
    "stockIntl": 497,
    "cartonType": "x6 pcs in carton box",
    "pcsPerCarton": 6,
    "priceEur": 4.88
  },
  {
    "id": "sup-amber:Model 12-180",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Model 12-180",
    "name": "Standard shape beer glass",
    "collection": "Amber Glass Lines",
    "category": "Tumblers & Highballs",
    "productionType": "Standard shape beer glass",
    "priceUsd": 5.3,
    "stockIntl": 580,
    "cartonType": "x6 pcs in carton box",
    "pcsPerCarton": 6,
    "priceEur": 4.88
  },
  {
    "id": "sup-amber:Model 20 - 1390C",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Model 20 - 1390C",
    "name": "Water glass with optic touch effect",
    "collection": "Amber Glass Lines",
    "category": "Tumblers & Highballs",
    "productionType": "Water glass with optic touch effect",
    "priceUsd": 4.2,
    "stockIntl": 1200,
    "cartonType": "x6 pcs in carton box",
    "pcsPerCarton": 6,
    "priceEur": 3.86
  },
  {
    "id": "sup-amber:Model 20-1453A",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Model 20-1453A",
    "name": "Standard shape water glass",
    "collection": "Amber Glass Lines",
    "category": "Tumblers & Highballs",
    "productionType": "Standard shape water glass",
    "priceUsd": 3.6,
    "stockIntl": 2680,
    "cartonType": "x6 pcs in carton box",
    "pcsPerCarton": 6,
    "priceEur": 3.31
  },
  {
    "id": "sup-amber:Model 20-3566",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Model 20-3566",
    "name": "Sake glass",
    "collection": "Amber Glass Lines",
    "category": "Hospitality Range",
    "productionType": "Sake glass",
    "priceUsd": 3.05,
    "stockIntl": 1100,
    "cartonType": "x6 pcs in carton box",
    "pcsPerCarton": 6,
    "priceEur": 2.81
  },
  {
    "id": "sup-amber:Glass/2350/300ml",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Glass/2350/300ml",
    "name": "Glass/2350/300ml",
    "collection": "HoReCa Line 1",
    "category": "Hospitality Range",
    "heightOrDiameter": "h 183/d 113",
    "totalMl": 300,
    "usableMl": 300,
    "priceUsd": 4.75,
    "stockIntl": 1029,
    "cartonType": "x6 pcs in carton box",
    "pcsPerCarton": 6,
    "imageKey": "/images/amber/Glass-2350-300ml.jpeg",
    "priceEur": 4.37
  },
  {
    "id": "sup-amber:Glass/2355/750ml",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Glass/2355/750ml",
    "name": "Glass/2355/750ml",
    "collection": "HoReCa Line 1",
    "category": "Hospitality Range",
    "heightOrDiameter": "h 287/d 103",
    "totalMl": 750,
    "usableMl": 750,
    "priceUsd": 5.4,
    "stockIntl": 1500,
    "cartonType": "x6 pcs in carton box",
    "pcsPerCarton": 6,
    "imageKey": "/images/amber/Glass-2355-750ml.jpeg",
    "priceEur": 4.97
  },
  {
    "id": "sup-amber:Glass/2670/600ml",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Glass/2670/600ml",
    "name": "Glass/2670/600ml",
    "collection": "HoReCa Line 1",
    "category": "Hospitality Range",
    "heightOrDiameter": "h 230/d 105",
    "totalMl": 600,
    "usableMl": 600,
    "priceUsd": 4.2,
    "stockIntl": 1500,
    "cartonType": "x6 pcs in carton box",
    "pcsPerCarton": 6,
    "imageKey": "/images/amber/Glass-2670-600ml.jpeg",
    "priceEur": 3.86
  },
  {
    "id": "sup-amber:Glass/2765/250ml",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Glass/2765/250ml",
    "name": "Glass/2765/250ml",
    "collection": "HoReCa Line 1",
    "category": "Hospitality Range",
    "heightOrDiameter": "h 155/d 93",
    "totalMl": 250,
    "usableMl": 250,
    "priceUsd": 4.2,
    "stockIntl": 2583,
    "cartonType": "x6 pcs in carton box",
    "pcsPerCarton": 6,
    "imageKey": "/images/amber/Glass-2765-250ml.jpeg",
    "priceEur": 3.86
  },
  {
    "id": "sup-amber:Glass/2872/140ml",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Glass/2872/140ml",
    "name": "Glass/2872/140ml",
    "collection": "HoReCa Line 1",
    "category": "Hospitality Range",
    "heightOrDiameter": "h 260/d 75",
    "totalMl": 140,
    "usableMl": 140,
    "priceUsd": 4.2,
    "stockIntl": 1600,
    "cartonType": "x6 pcs in carton box",
    "pcsPerCarton": 6,
    "imageKey": "/images/amber/Glass-2872-140ml.jpeg",
    "priceEur": 3.86
  },
  {
    "id": "sup-amber:Glass/2878/1000ml",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Glass/2878/1000ml",
    "name": "Glass/2878/1000ml",
    "collection": "HoReCa Line 1",
    "category": "Hospitality Range",
    "heightOrDiameter": "h 250/d 122",
    "totalMl": 1000,
    "usableMl": 1000,
    "priceUsd": 5.4,
    "stockIntl": 7000,
    "cartonType": "x6 pcs in carton box",
    "pcsPerCarton": 6,
    "imageKey": "/images/amber/Glass-2878-1000ml.jpeg",
    "priceEur": 4.97
  },
  {
    "id": "sup-amber:Glass/2975/200ml",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Glass/2975/200ml",
    "name": "Glass/2975/200ml",
    "collection": "HoReCa Line 1",
    "category": "Hospitality Range",
    "heightOrDiameter": "h 135/d 102",
    "totalMl": 200,
    "usableMl": 200,
    "priceUsd": 4.2,
    "stockIntl": 1600,
    "cartonType": "x6 pcs in carton box",
    "pcsPerCarton": 6,
    "imageKey": "/images/amber/Glass-2975-200ml.jpeg",
    "priceEur": 3.86
  },
  {
    "id": "sup-amber:Glass/3104/optyk/280ml",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Glass/3104/optyk/280ml",
    "name": "Glass/3104/optyk/280ml",
    "collection": "HoReCa Line 1",
    "category": "Hospitality Range",
    "heightOrDiameter": "h 160/d 105",
    "totalMl": 280,
    "usableMl": 280,
    "priceUsd": 4.75,
    "stockIntl": 2600,
    "cartonType": "x6 pcs in carton box",
    "pcsPerCarton": 6,
    "imageKey": "/images/amber/Glass-3104-optyk-280ml.jpeg",
    "priceEur": 4.37
  },
  {
    "id": "sup-amber:Glass/3500/250ml",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Glass/3500/250ml",
    "name": "Glass/3500/250ml",
    "collection": "HoReCa Line 1",
    "category": "Hospitality Range",
    "heightOrDiameter": "h 200/d 100",
    "totalMl": 250,
    "usableMl": 250,
    "priceUsd": 3.75,
    "stockIntl": 1100,
    "cartonType": "x6 pcs in carton box",
    "pcsPerCarton": 6,
    "imageKey": "/images/amber/Glass-3500-250ml.jpeg",
    "priceEur": 3.45
  },
  {
    "id": "sup-amber:Glass/3566/140ml",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Glass/3566/140ml",
    "name": "Glass/3566/140ml",
    "collection": "HoReCa Line 1",
    "category": "Hospitality Range",
    "heightOrDiameter": "h 78/d 82",
    "totalMl": 140,
    "usableMl": 140,
    "priceUsd": 3.05,
    "stockIntl": 1130,
    "cartonType": "x6 pcs in carton box",
    "pcsPerCarton": 6,
    "imageKey": "/images/amber/Glass-3566-140ml.jpeg",
    "priceEur": 2.81
  },
  {
    "id": "sup-amber:Glass/1113/B/250ml",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Glass/1113/B/250ml",
    "name": "Glass/1113/B/250ml",
    "collection": "HoReCa Line 1",
    "category": "Hospitality Range",
    "heightOrDiameter": "h 155/d 70",
    "totalMl": 250,
    "usableMl": 250,
    "priceUsd": 3.75,
    "stockIntl": 1100,
    "cartonType": "x6 pcs in carton box",
    "pcsPerCarton": 6,
    "imageKey": "/images/amber/Glass-1113-B-250ml.jpeg",
    "priceEur": 3.45
  },
  {
    "id": "sup-amber:Glass/1390/C/optyk/300ml",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Glass/1390/C/optyk/300ml",
    "name": "Glass/1390/C/optyk/300ml",
    "collection": "HoReCa Line 1",
    "category": "Hospitality Range",
    "heightOrDiameter": "h 130/d 68",
    "totalMl": 300,
    "usableMl": 300,
    "priceUsd": 4.2,
    "stockIntl": 1200,
    "cartonType": "x6 pcs in carton box",
    "pcsPerCarton": 6,
    "imageKey": "/images/amber/Glass-1390-C-optyk-300ml.jpeg",
    "priceEur": 3.86
  },
  {
    "id": "sup-amber:Glass/1453/300ml",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Glass/1453/300ml",
    "name": "Glass/1453/300ml",
    "collection": "HoReCa Line 1",
    "category": "Hospitality Range",
    "heightOrDiameter": "h 95/d 80",
    "totalMl": 300,
    "usableMl": 300,
    "priceUsd": 3.6,
    "stockIntl": 6500,
    "cartonType": "x6 pcs in carton box",
    "pcsPerCarton": 6,
    "imageKey": "/images/amber/Glass-1453-300ml.jpeg",
    "priceEur": 3.31
  },
  {
    "id": "sup-amber:Glass/1453/A/350ml",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Glass/1453/A/350ml",
    "name": "Glass/1453/A/350ml",
    "collection": "HoReCa Line 1",
    "category": "Hospitality Range",
    "heightOrDiameter": "h 180/d 65",
    "totalMl": 350,
    "usableMl": 350,
    "priceUsd": 3.6,
    "stockIntl": 2680,
    "cartonType": "x6 pcs in carton box",
    "pcsPerCarton": 6,
    "imageKey": "/images/amber/Glass-1453-A-350ml.jpeg",
    "priceEur": 3.31
  },
  {
    "id": "sup-amber:Glass/1462/optyk/400ml",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Glass/1462/optyk/400ml",
    "name": "Glass/1462/optyk/400ml",
    "collection": "HoReCa Line 1",
    "category": "Hospitality Range",
    "heightOrDiameter": "h 140/d 70",
    "totalMl": 400,
    "usableMl": 400,
    "priceUsd": 4.2,
    "stockIntl": 600,
    "cartonType": "x6 pcs in carton box",
    "pcsPerCarton": 6,
    "imageKey": "/images/amber/Glass-1462-optyk-400ml.jpeg",
    "priceEur": 3.86
  },
  {
    "id": "sup-amber:Glass/292/C/300ml",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Glass/292/C/300ml",
    "name": "Glass/292/C/300ml",
    "collection": "HoReCa Line 1",
    "category": "Hospitality Range",
    "heightOrDiameter": "h 160/d 70",
    "totalMl": 300,
    "usableMl": 300,
    "priceUsd": 3.6,
    "stockIntl": 1500,
    "cartonType": "x6 pcs in carton box",
    "pcsPerCarton": 6,
    "imageKey": "/images/amber/Glass-292-C-300ml.jpeg",
    "priceEur": 3.31
  },
  {
    "id": "sup-amber:Glass/2276/A/optyk/600ml",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Glass/2276/A/optyk/600ml",
    "name": "Glass/2276/A/optyk/600ml",
    "collection": "HoReCa Line 1",
    "category": "Hospitality Range",
    "heightOrDiameter": "h 287/d 102",
    "totalMl": 600,
    "usableMl": 600,
    "priceUsd": 5.3,
    "stockIntl": 1200,
    "cartonType": "x6 pcs in carton box",
    "pcsPerCarton": 6,
    "imageKey": "/images/amber/Glass-2276-A-optyk-600ml.jpeg",
    "priceEur": 4.88
  },
  {
    "id": "sup-amber:Glass/180/500ml",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Glass/180/500ml",
    "name": "Glass/180/500ml",
    "collection": "HoReCa Line 1",
    "category": "Hospitality Range",
    "heightOrDiameter": "h 140/d 90",
    "totalMl": 500,
    "usableMl": 500,
    "priceUsd": 5.3,
    "stockIntl": 580,
    "cartonType": "x6 pcs in carton box",
    "pcsPerCarton": 6,
    "imageKey": "/images/amber/Glass-180-500ml.jpeg",
    "priceEur": 4.88
  },
  {
    "id": "sup-amber:Glass/259/500ml",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Glass/259/500ml",
    "name": "Glass/259/500ml",
    "collection": "HoReCa Line 1",
    "category": "Hospitality Range",
    "heightOrDiameter": "h 130/ d103",
    "totalMl": 500,
    "usableMl": 500,
    "priceUsd": 5.3,
    "stockIntl": 800,
    "cartonType": "x6 pcs in carton box",
    "pcsPerCarton": 6,
    "imageKey": "/images/amber/Glass-259-500ml.jpeg",
    "priceEur": 4.88
  },
  {
    "id": "sup-amber:Glass/313/700ml",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Glass/313/700ml",
    "name": "Glass/313/700ml",
    "collection": "HoReCa Line 1",
    "category": "Hospitality Range",
    "heightOrDiameter": "h 150/ d 103",
    "totalMl": 700,
    "usableMl": 700,
    "priceUsd": 5.3,
    "stockIntl": 450,
    "cartonType": "x6 pcs in carton box",
    "pcsPerCarton": 6,
    "imageKey": "/images/amber/Glass-313-700ml.jpeg",
    "priceEur": 4.88
  },
  {
    "id": "sup-amber:Glass/23/281/A/500ml",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Glass/23/281/A/500ml",
    "name": "Glass/23/281/A/500ml",
    "collection": "HoReCa Line 1",
    "category": "Hospitality Range",
    "heightOrDiameter": "h 240/ d 73",
    "totalMl": 500,
    "usableMl": 500,
    "priceUsd": 5.3,
    "stockIntl": 500,
    "cartonType": "x6 pcs in carton box",
    "pcsPerCarton": 6,
    "imageKey": "/images/amber/Glass-23-281-A-500ml.jpeg",
    "priceEur": 4.88
  },
  {
    "id": "sup-amber:Glass/3388/A/270ml",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Glass/3388/A/270ml",
    "name": "Glass/3388/A/270ml",
    "collection": "HoReCa Line 2",
    "category": "Hospitality Range",
    "heightOrDiameter": "h 152/d 120",
    "totalMl": 270,
    "usableMl": 270,
    "priceUsd": 4.2,
    "stockIntl": 500,
    "cartonType": "x6 pcs in carton box",
    "pcsPerCarton": 6,
    "imageKey": "/images/amber/Glass-3388-A-270ml.jpeg",
    "priceEur": 3.86
  },
  {
    "id": "sup-amber:Glass/3104/C/optyk/24/230ml",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Glass/3104/C/optyk/24/230ml",
    "name": "Glass/3104/C/optyk/24/230ml",
    "collection": "HoReCa Line 2",
    "category": "Hospitality Range",
    "heightOrDiameter": "h 232/d 62",
    "totalMl": 230,
    "usableMl": 230,
    "priceUsd": 4.75,
    "stockIntl": 402,
    "cartonType": "x6 pcs in carton box",
    "pcsPerCarton": 6,
    "imageKey": "/images/amber/Glass-3104-C-optyk-24-230ml.jpeg",
    "priceEur": 4.37
  },
  {
    "id": "sup-amber:Glass/3104/C/optyk/8/230ml",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Glass/3104/C/optyk/8/230ml",
    "name": "Glass/3104/C/optyk/8/230ml",
    "collection": "HoReCa Line 2",
    "category": "Hospitality Range",
    "heightOrDiameter": "h 232/d 62",
    "totalMl": 230,
    "usableMl": 230,
    "priceUsd": 4.75,
    "stockIntl": 678,
    "cartonType": "x6 pcs in carton box",
    "pcsPerCarton": 6,
    "imageKey": "/images/amber/Glass-3104-C-optyk-8-230ml.jpeg",
    "priceEur": 4.37
  },
  {
    "id": "sup-amber:Glass/3223/optyk/150ml",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Glass/3223/optyk/150ml",
    "name": "Glass/3223/optyk/150ml",
    "collection": "HoReCa Line 2",
    "category": "Hospitality Range",
    "heightOrDiameter": "h 175/d 110",
    "totalMl": 150,
    "usableMl": 150,
    "priceUsd": 4.75,
    "stockIntl": 324,
    "cartonType": "x6 pcs in carton box",
    "pcsPerCarton": 6,
    "imageKey": "/images/amber/Glass-3223-optyk-150ml.jpeg",
    "priceEur": 4.37
  },
  {
    "id": "sup-amber:Glass/3224/optyk/150ml",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Glass/3224/optyk/150ml",
    "name": "Glass/3224/optyk/150ml",
    "collection": "HoReCa Line 2",
    "category": "Hospitality Range",
    "heightOrDiameter": "h 180/d 105",
    "totalMl": 150,
    "usableMl": 150,
    "priceUsd": 4.75,
    "stockIntl": 396,
    "cartonType": "x6 pcs in carton box",
    "pcsPerCarton": 6,
    "imageKey": "/images/amber/Glass-3224-optyk-150ml.jpeg",
    "priceEur": 4.37
  },
  {
    "id": "sup-amber:Glass/3248/750ml",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Glass/3248/750ml",
    "name": "Glass/3248/750ml",
    "collection": "HoReCa Line 2",
    "category": "Hospitality Range",
    "heightOrDiameter": "h 185/d 125",
    "totalMl": 750,
    "usableMl": 750,
    "priceUsd": 6.4,
    "stockIntl": 372,
    "cartonType": "x6 pcs in carton box",
    "pcsPerCarton": 6,
    "imageKey": "/images/amber/Glass-3248-750ml.jpeg",
    "priceEur": 5.89
  },
  {
    "id": "sup-amber:Glass/3254/F/280ml",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Glass/3254/F/280ml",
    "name": "Glass/3254/F/280ml",
    "collection": "HoReCa Line 2",
    "category": "Hospitality Range",
    "heightOrDiameter": "h 210/d 95",
    "totalMl": 280,
    "usableMl": 280,
    "priceUsd": 4.2,
    "stockIntl": 900,
    "cartonType": "x6 pcs in carton box",
    "pcsPerCarton": 6,
    "imageKey": "/images/amber/Glass-3254-F-280ml.jpeg",
    "priceEur": 3.86
  },
  {
    "id": "sup-amber:Glass/3645/A/490ml",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Glass/3645/A/490ml",
    "name": "Glass/3645/A/490ml",
    "collection": "HoReCa Line 2",
    "category": "Hospitality Range",
    "heightOrDiameter": "h 190/d 88",
    "totalMl": 490,
    "usableMl": 490,
    "priceUsd": 3.9,
    "stockIntl": 372,
    "cartonType": "x6 pcs in carton box",
    "pcsPerCarton": 6,
    "imageKey": "/images/amber/Glass-3645-A-490ml.jpeg",
    "priceEur": 3.59
  },
  {
    "id": "sup-amber:Glass/3645/B/600ml",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Glass/3645/B/600ml",
    "name": "Glass/3645/B/600ml",
    "collection": "HoReCa Line 2",
    "category": "Hospitality Range",
    "heightOrDiameter": "h 209/d 91",
    "totalMl": 600,
    "usableMl": 600,
    "priceUsd": 4.2,
    "stockIntl": 280,
    "cartonType": "x6 pcs in carton box",
    "pcsPerCarton": 6,
    "imageKey": "/images/amber/Glass-3645-B-600ml.jpeg",
    "priceEur": 3.86
  },
  {
    "id": "sup-amber:Glass/3645/230ml",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Glass/3645/230ml",
    "name": "Glass/3645/230ml",
    "collection": "HoReCa Line 2",
    "category": "Hospitality Range",
    "heightOrDiameter": "h 127/d 98",
    "totalMl": 230,
    "usableMl": 230,
    "priceUsd": 3.7,
    "stockIntl": 222,
    "cartonType": "x6 pcs in carton box",
    "pcsPerCarton": 6,
    "imageKey": "/images/amber/Glass-3645-230ml.jpeg",
    "priceEur": 3.4
  },
  {
    "id": "sup-amber:Glass/3297/A/140ml",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Glass/3297/A/140ml",
    "name": "Glass/3297/A/140ml",
    "collection": "HoReCa Line 2",
    "category": "Hospitality Range",
    "heightOrDiameter": "h 150/d 82",
    "totalMl": 140,
    "usableMl": 140,
    "priceUsd": 3.7,
    "stockIntl": 352,
    "cartonType": "x6 pcs in carton box",
    "pcsPerCarton": 6,
    "imageKey": "/images/amber/Glass-3297-A-140ml.jpeg",
    "priceEur": 3.4
  },
  {
    "id": "sup-amber:Glass/3297/40ml",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Glass/3297/40ml",
    "name": "Glass/3297/40ml",
    "collection": "HoReCa Line 2",
    "category": "Hospitality Range",
    "heightOrDiameter": "h 110/d 55",
    "totalMl": 40,
    "usableMl": 40,
    "priceUsd": 3.35,
    "stockIntl": 432,
    "cartonType": "x6 pcs in carton box",
    "pcsPerCarton": 6,
    "imageKey": "/images/amber/Glass-3297-40ml.jpeg",
    "priceEur": 3.08
  },
  {
    "id": "sup-amber:Glass/2338/160ml",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Glass/2338/160ml",
    "name": "Glass/2338/160ml",
    "collection": "HoReCa Line 2",
    "category": "Hospitality Range",
    "heightOrDiameter": "h 174/d 62",
    "totalMl": 160,
    "usableMl": 160,
    "priceUsd": 3.35,
    "stockIntl": 900,
    "cartonType": "x6 pcs in carton box",
    "pcsPerCarton": 6,
    "imageKey": "/images/amber/Glass-2338-160ml.jpeg",
    "priceEur": 3.08
  },
  {
    "id": "sup-amber:Glass/3053/200ml",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Glass/3053/200ml",
    "name": "Glass/3053/200ml",
    "collection": "HoReCa Line 2",
    "category": "Hospitality Range",
    "heightOrDiameter": "h 193/d 65",
    "totalMl": 200,
    "usableMl": 200,
    "priceUsd": 3.75,
    "stockIntl": 510,
    "cartonType": "x6 pcs in carton box",
    "pcsPerCarton": 6,
    "imageKey": "/images/amber/Glass-3053-200ml.jpeg",
    "priceEur": 3.45
  },
  {
    "id": "sup-amber:Glass/3053/A/300ml",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Glass/3053/A/300ml",
    "name": "Glass/3053/A/300ml",
    "collection": "HoReCa Line 2",
    "category": "Hospitality Range",
    "heightOrDiameter": "h 185/d 82",
    "totalMl": 300,
    "usableMl": 300,
    "priceUsd": 3.9,
    "stockIntl": 900,
    "cartonType": "x6 pcs in carton box",
    "pcsPerCarton": 6,
    "imageKey": "/images/amber/Glass-3053-A-300ml.jpeg",
    "priceEur": 3.59
  },
  {
    "id": "sup-amber:Glass/3307/345ml",
    "status": "approved",
    "supplier": "Amber Glass",
    "supplierId": "sup-amber",
    "createdAt": 0,
    "sku": "Glass/3307/345ml",
    "name": "Glass/3307/345ml",
    "collection": "HoReCa Line 2",
    "category": "Hospitality Range",
    "heightOrDiameter": "h 277/d 75",
    "totalMl": 345,
    "usableMl": 345,
    "priceUsd": 6.4,
    "stockIntl": 378,
    "cartonType": "x6 pcs in carton box",
    "pcsPerCarton": 6,
    "imageKey": "/images/amber/Glass-3307-345ml.jpeg",
    "priceEur": 5.89
  }
];
