// AUTO-GENERATED from public/solbika/*.xlsx — Solbika vendor catalog seed.
// Regenerate with: node scripts/gen-solbika-seed.mjs
import type { Product } from './products';

export const SOLBIKA_PRODUCTS: Product[] = [
  {
    "id": "sup-solbika:70402",
    "sku": "70402",
    "baseIndex": "70402",
    "name": "Drinking Glass",
    "collection": "Always Available",
    "category": "HoReCa",
    "productionType": "machine",
    "heightOrDiameter": "h95 d87",
    "usableMl": 280,
    "usableOz": 9.5,
    "totalMl": 280,
    "totalOz": 9.5,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 1430,
    "priceEur": 0.51,
    "priceUsd": 0.5916,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/70402.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:70412",
    "sku": "70412",
    "baseIndex": "70412",
    "name": "Drinking Glass",
    "collection": "Always Available",
    "category": "HoReCa",
    "productionType": "machine",
    "heightOrDiameter": "h148 d78",
    "usableMl": 425,
    "usableOz": 14.3,
    "totalMl": 425,
    "totalOz": 14.3,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 920,
    "priceEur": 0.7,
    "priceUsd": 0.8119999999999999,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/70412.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:70414",
    "sku": "70414",
    "baseIndex": "70414",
    "name": "Drinking Glass",
    "collection": "Always Available",
    "category": "HoReCa",
    "productionType": "machine",
    "heightOrDiameter": "h148 d78",
    "usableMl": 380,
    "usableOz": 12.8,
    "totalMl": 380,
    "totalOz": 12.8,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 1134,
    "priceEur": 0.72,
    "priceUsd": 0.8351999999999999,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/70414.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:41308",
    "sku": "41308",
    "baseIndex": "41308",
    "name": "Bowl",
    "collection": "Always Available",
    "category": "HoReCa",
    "productionType": "machine",
    "heightOrDiameter": "h130 d235",
    "usableMl": 3570,
    "usableOz": 120.7,
    "totalMl": 3570,
    "totalOz": 120.7,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 288,
    "priceEur": 1.54,
    "priceUsd": 1.7864,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/41308.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:72075",
    "sku": "72075",
    "baseIndex": "72075",
    "name": "Drinking Glass",
    "collection": "Always Available",
    "category": "HoReCa",
    "productionType": "machine",
    "heightOrDiameter": "h144 d84",
    "usableMl": 410,
    "usableOz": 13.8,
    "totalMl": 410,
    "totalOz": 13.8,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 996,
    "priceEur": 0.68,
    "priceUsd": 0.7888000000000001,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/72075.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:72073",
    "sku": "72073",
    "baseIndex": "72073",
    "name": "Drinking Glass",
    "collection": "Always Available",
    "category": "HoReCa",
    "productionType": "machine",
    "heightOrDiameter": "h144 d83",
    "usableMl": 410,
    "usableOz": 13.8,
    "totalMl": 410,
    "totalOz": 13.8,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 996,
    "priceEur": 0.71,
    "priceUsd": 0.8235999999999999,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/72073.jpg",
    "images": [
      "/images/solbika/72073.jpg",
      "/images/solbika/72073-2.png"
    ],
    "createdAt": 0
  },
  {
    "id": "sup-solbika:41307",
    "sku": "41307",
    "baseIndex": "41307",
    "name": "Bowl",
    "collection": "Always Available",
    "category": "HoReCa",
    "productionType": "machine",
    "heightOrDiameter": "h92 d166",
    "usableMl": 1000,
    "usableOz": 33.8,
    "totalMl": 1000,
    "totalOz": 33.8,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 864,
    "priceEur": 0.84,
    "priceUsd": 0.9743999999999999,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/41307.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:38009",
    "sku": "38009",
    "baseIndex": "38009",
    "name": "Beer Glass",
    "collection": "Always Available",
    "category": "HoReCa",
    "productionType": "machine",
    "heightOrDiameter": "h184 d76",
    "usableMl": 650,
    "usableOz": 21.9,
    "totalMl": 650,
    "totalOz": 21.9,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 894,
    "priceEur": 0.99,
    "priceUsd": 1.1483999999999999,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/38009.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:38008",
    "sku": "38008",
    "baseIndex": "38008",
    "name": "Beer Glass",
    "collection": "Always Available",
    "category": "HoReCa",
    "productionType": "machine",
    "heightOrDiameter": "h148 d70",
    "usableMl": 385,
    "usableOz": 13,
    "totalMl": 385,
    "totalOz": 13,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 1344,
    "priceEur": 0.63,
    "priceUsd": 0.7308,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/38008.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:38443",
    "sku": "38443",
    "baseIndex": "38443",
    "name": "Drinking Glass",
    "collection": "Always Available",
    "category": "HoReCa",
    "productionType": "machine",
    "heightOrDiameter": "h125 d78",
    "usableMl": 620,
    "usableOz": 20.9,
    "totalMl": 620,
    "totalOz": 20.9,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 864,
    "priceEur": 0.64,
    "priceUsd": 0.7424,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/38443.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:35708",
    "sku": "35708",
    "baseIndex": "35708",
    "name": "Decanter",
    "collection": "Always Available",
    "category": "HoReCa",
    "productionType": "machine",
    "heightOrDiameter": "h250 d75",
    "usableMl": 1150,
    "usableOz": 38.8,
    "totalMl": 1150,
    "totalOz": 38.8,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 336,
    "priceEur": 1.32,
    "priceUsd": 1.5312,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/35708.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:35709",
    "sku": "35709",
    "baseIndex": "35709",
    "name": "Decanter",
    "collection": "Always Available",
    "category": "HoReCa",
    "productionType": "machine",
    "heightOrDiameter": "h250 d74",
    "usableMl": 1150,
    "usableOz": 38.8,
    "totalMl": 1150,
    "totalOz": 38.8,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 216,
    "priceEur": 1.32,
    "priceUsd": 1.5312,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/35709.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:38445",
    "sku": "38445",
    "baseIndex": "38445",
    "name": "Drinking Glass",
    "collection": "Always Available",
    "category": "HoReCa",
    "productionType": "machine",
    "heightOrDiameter": "h125 d96",
    "usableMl": 620,
    "usableOz": 20.9,
    "totalMl": 620,
    "totalOz": 20.9,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 864,
    "priceEur": 0.59,
    "priceUsd": 0.6843999999999999,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/38445.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:38032",
    "sku": "38032",
    "baseIndex": "38032",
    "name": "Ice Cream Cup",
    "collection": "Always Available",
    "category": "HoReCa",
    "productionType": "machine",
    "heightOrDiameter": "h110 d110",
    "usableMl": 500,
    "usableOz": 16.9,
    "totalMl": 500,
    "totalOz": 16.9,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 720,
    "priceEur": 0.8,
    "priceUsd": 0.9279999999999999,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/38032.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:38034",
    "sku": "38034",
    "baseIndex": "38034",
    "name": "Ice Cream Cup",
    "collection": "Always Available",
    "category": "HoReCa",
    "productionType": "machine",
    "heightOrDiameter": "h110 d110",
    "usableMl": 490,
    "usableOz": 16.5,
    "totalMl": 490,
    "totalOz": 16.5,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 486,
    "priceEur": 0.68,
    "priceUsd": 0.7888000000000001,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/38034.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:38449",
    "sku": "38449",
    "baseIndex": "38449",
    "name": "Drinking Glass",
    "collection": "Always Available",
    "category": "HoReCa",
    "productionType": "machine",
    "heightOrDiameter": "h136 d68",
    "usableMl": 540,
    "usableOz": 18.2,
    "totalMl": 540,
    "totalOz": 18.2,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 1280,
    "priceEur": 0.53,
    "priceUsd": 0.6148,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/38449.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:41361",
    "sku": "41361",
    "baseIndex": "41361",
    "name": "Bowl",
    "collection": "Always Available",
    "category": "HoReCa",
    "productionType": "machine",
    "heightOrDiameter": "h68 d143",
    "usableMl": 655,
    "usableOz": 22.1,
    "totalMl": 655,
    "totalOz": 22.1,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 1050,
    "priceEur": 0.64,
    "priceUsd": 0.7424,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/41361.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:70427",
    "sku": "70427",
    "baseIndex": "70427",
    "name": "Whisky Glass",
    "collection": "Always Available",
    "category": "HoReCa",
    "productionType": "machine",
    "heightOrDiameter": "h95 d85",
    "usableMl": 330,
    "usableOz": 11.1,
    "totalMl": 330,
    "totalOz": 11.1,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 1488,
    "priceEur": 0.7,
    "priceUsd": 0.8119999999999999,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/70427.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:41448",
    "sku": "41448",
    "baseIndex": "41448",
    "name": "Plate",
    "collection": "Always Available",
    "category": "HoReCa",
    "productionType": "machine",
    "heightOrDiameter": "h24 d300",
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 630,
    "priceEur": 1.53,
    "priceUsd": 1.7748,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/41448.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:41444",
    "sku": "41444",
    "baseIndex": "41444",
    "name": "Plate",
    "collection": "Always Available",
    "category": "HoReCa",
    "productionType": "machine",
    "heightOrDiameter": "h15 d174",
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 2880,
    "priceEur": 0.46,
    "priceUsd": 0.5336,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/41444.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:38446",
    "sku": "38446",
    "baseIndex": "38446",
    "name": "Drinking Glass",
    "collection": "Always Available",
    "category": "HoReCa",
    "productionType": "machine",
    "heightOrDiameter": "h96 d69",
    "usableMl": 360,
    "usableOz": 12.1,
    "totalMl": 360,
    "totalOz": 12.1,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 1760,
    "priceEur": 0.46,
    "priceUsd": 0.5336,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/38446.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:38448",
    "sku": "38448",
    "baseIndex": "38448",
    "name": "Drinking Glass",
    "collection": "Always Available",
    "category": "HoReCa",
    "productionType": "machine",
    "heightOrDiameter": "h96 d77",
    "usableMl": 350,
    "usableOz": 11.8,
    "totalMl": 350,
    "totalOz": 11.8,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 1760,
    "priceEur": 0.46,
    "priceUsd": 0.5336,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/38448.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:74414",
    "sku": "74414",
    "baseIndex": "74414",
    "name": "Jug",
    "collection": "Always Available",
    "category": "HoReCa",
    "productionType": "machine",
    "heightOrDiameter": "h190 d190",
    "usableMl": 1230,
    "usableOz": 41.5,
    "totalMl": 1230,
    "totalOz": 41.5,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 204,
    "priceEur": 2.67,
    "priceUsd": 3.0971999999999995,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/74414.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:74440",
    "sku": "74440",
    "baseIndex": "74440",
    "name": "Beer Glass",
    "collection": "Always Available",
    "category": "HoReCa",
    "productionType": "machine",
    "heightOrDiameter": "h134 d94",
    "usableMl": 610,
    "usableOz": 20.6,
    "totalMl": 610,
    "totalOz": 20.6,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 560,
    "priceEur": 1.55,
    "priceUsd": 1.7979999999999998,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/74440.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:70426",
    "sku": "70426",
    "baseIndex": "70426",
    "name": "Drinking Glass",
    "collection": "Always Available",
    "category": "HoReCa",
    "productionType": "machine",
    "heightOrDiameter": "h145 d78",
    "usableMl": 384,
    "usableOz": 12.9,
    "totalMl": 384,
    "totalOz": 12.9,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 1078,
    "priceEur": 0.81,
    "priceUsd": 0.9396,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/70426.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:70409",
    "sku": "70409",
    "baseIndex": "70409",
    "name": "Drinking Glass",
    "collection": "Always Available",
    "category": "HoReCa",
    "productionType": "machine",
    "heightOrDiameter": "h180 d100",
    "usableMl": 700,
    "usableOz": 23.6,
    "totalMl": 700,
    "totalOz": 23.6,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 624,
    "priceEur": 1.2,
    "priceUsd": 1.392,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/70409.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:38447",
    "sku": "38447",
    "baseIndex": "38447",
    "name": "Drinking Glass",
    "collection": "Always Available",
    "category": "HoReCa",
    "productionType": "machine",
    "heightOrDiameter": "h136 d69",
    "usableMl": 540,
    "usableOz": 18.2,
    "totalMl": 540,
    "totalOz": 18.2,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 1280,
    "priceEur": 0.52,
    "priceUsd": 0.6032,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/38447.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:41302",
    "sku": "41302",
    "baseIndex": "41302",
    "name": "Bowl",
    "collection": "Always Available",
    "category": "HoReCa",
    "productionType": "machine",
    "heightOrDiameter": "h113 d200",
    "usableMl": 1660,
    "usableOz": 56.1,
    "totalMl": 1660,
    "totalOz": 56.1,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 450,
    "priceEur": 1.08,
    "priceUsd": 1.2528,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/41302.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:41369",
    "sku": "41369",
    "baseIndex": "41369",
    "name": "Bowl",
    "collection": "Always Available",
    "category": "HoReCa",
    "productionType": "machine",
    "heightOrDiameter": "h98 d217",
    "usableMl": 2320,
    "usableOz": 78.4,
    "totalMl": 2320,
    "totalOz": 78.4,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 360,
    "priceEur": 1.1,
    "priceUsd": 1.276,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/41369.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:70114",
    "sku": "70114",
    "baseIndex": "70114",
    "name": "Shot Glass",
    "collection": "Always Available",
    "category": "HoReCa",
    "productionType": "machine",
    "heightOrDiameter": "h68 d38",
    "usableMl": 30,
    "usableOz": 1,
    "totalMl": 30,
    "totalOz": 1,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 8944,
    "priceEur": 0.19,
    "priceUsd": 0.22039999999999998,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/70114.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:70210",
    "sku": "70210",
    "baseIndex": "70210",
    "name": "Cube",
    "collection": "Always Available",
    "category": "Candle Glass",
    "productionType": "machine",
    "heightOrDiameter": "h80 d80",
    "usableMl": 310,
    "usableOz": 10.4,
    "totalMl": 310,
    "totalOz": 10.4,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 1638,
    "priceEur": 0.68,
    "priceUsd": 0.7888000000000001,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/70210.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:70822",
    "sku": "70822",
    "baseIndex": "70822",
    "name": "Cylinder",
    "collection": "Always Available",
    "category": "Candle Glass",
    "productionType": "machine",
    "heightOrDiameter": "h100 d100",
    "usableMl": 520,
    "usableOz": 17.5,
    "totalMl": 520,
    "totalOz": 17.5,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 1040,
    "priceEur": 0.8,
    "priceUsd": 0.9279999999999999,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/70822.jpg",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:70842",
    "sku": "70842",
    "baseIndex": "70842",
    "name": "Cylinder Heavy",
    "collection": "Always Available",
    "category": "Candle Glass",
    "productionType": "machine",
    "heightOrDiameter": "h80 d90",
    "usableMl": 250,
    "usableOz": 8.4,
    "totalMl": 250,
    "totalOz": 8.4,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 1375,
    "priceEur": 0.85,
    "priceUsd": 0.9859999999999999,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/70842.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:70848",
    "sku": "70848",
    "baseIndex": "70848",
    "name": "Cylinder",
    "collection": "Always Available",
    "category": "Candle Glass",
    "productionType": "machine",
    "heightOrDiameter": "h97 d79",
    "usableMl": 290,
    "usableOz": 9.8,
    "totalMl": 290,
    "totalOz": 9.8,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 1760,
    "priceEur": 0.63,
    "priceUsd": 0.7308,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/70848.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:71423",
    "sku": "71423",
    "baseIndex": "71423",
    "name": "Cylinder",
    "collection": "Always Available",
    "category": "Candle Glass",
    "productionType": "machine",
    "heightOrDiameter": "h75 d77",
    "usableMl": 210,
    "usableOz": 7.1,
    "totalMl": 210,
    "totalOz": 7.1,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 2310,
    "priceEur": 0.38,
    "priceUsd": 0.44079999999999997,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/71423.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:71831",
    "sku": "71831",
    "baseIndex": "71831",
    "name": "Cylinder",
    "collection": "Always Available",
    "category": "Candle Glass",
    "productionType": "machine",
    "heightOrDiameter": "h110 d96",
    "usableMl": 510,
    "usableOz": 17.2,
    "totalMl": 510,
    "totalOz": 17.2,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 936,
    "priceEur": 0.81,
    "priceUsd": 0.9396,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/71831.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:70803",
    "sku": "70803",
    "baseIndex": "70803",
    "name": "Cylinder",
    "collection": "Always Available",
    "category": "Candle Glass",
    "productionType": "machine",
    "heightOrDiameter": "h95 d90",
    "usableMl": 390,
    "usableOz": 13.1,
    "totalMl": 390,
    "totalOz": 13.1,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 1375,
    "priceEur": 0.64,
    "priceUsd": 0.7424,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/70803.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:70045",
    "sku": "70045",
    "baseIndex": "70045",
    "name": "Cylinder",
    "collection": "Always Available",
    "category": "Candle Glass",
    "productionType": "machine",
    "heightOrDiameter": "h65 d70",
    "usableMl": 160,
    "usableOz": 5.4,
    "totalMl": 160,
    "totalOz": 5.4,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 3440,
    "priceEur": 0.32,
    "priceUsd": 0.3712,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/70045.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:70440",
    "sku": "70440",
    "baseIndex": "70440",
    "name": "Cylinder",
    "collection": "Always Available",
    "category": "Candle Glass",
    "productionType": "machine",
    "heightOrDiameter": "h66 d58",
    "usableMl": 100,
    "usableOz": 3.3,
    "totalMl": 100,
    "totalOz": 3.3,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 4500,
    "priceEur": 0.27,
    "priceUsd": 0.3132,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/70440.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:70110",
    "sku": "70110",
    "baseIndex": "70110",
    "name": "Conical",
    "collection": "Always Available",
    "category": "Candle Glass",
    "productionType": "machine",
    "heightOrDiameter": "h65 d70",
    "usableMl": 130,
    "usableOz": 4.3,
    "totalMl": 130,
    "totalOz": 4.3,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 3225,
    "priceEur": 0.33,
    "priceUsd": 0.3828,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/70110.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:70808",
    "sku": "70808",
    "baseIndex": "70808",
    "name": "Cylinder",
    "collection": "Always Available",
    "category": "Candle Glass",
    "productionType": "machine",
    "heightOrDiameter": "h88 d80",
    "usableMl": 280,
    "usableOz": 9.4,
    "totalMl": 280,
    "totalOz": 9.4,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 1760,
    "priceEur": 0.51,
    "priceUsd": 0.5916,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/70808.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:70056",
    "sku": "70056",
    "baseIndex": "70056",
    "name": "Cylinder",
    "collection": "Always Available",
    "category": "Candle Glass",
    "productionType": "machine",
    "heightOrDiameter": "h78 d71",
    "usableMl": 205,
    "usableOz": 6.9,
    "totalMl": 205,
    "totalOz": 6.9,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 2496,
    "priceEur": 0.38,
    "priceUsd": 0.44079999999999997,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/70056.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:70072",
    "sku": "70072",
    "baseIndex": "70072",
    "name": "Conical",
    "collection": "Always Available",
    "category": "Candle Glass",
    "productionType": "machine",
    "heightOrDiameter": "h73 d76",
    "usableMl": 180,
    "usableOz": 6,
    "totalMl": 180,
    "totalOz": 6,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 2520,
    "priceEur": 0.33,
    "priceUsd": 0.3828,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/70072.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:70078",
    "sku": "70078",
    "baseIndex": "70078",
    "name": "Conical",
    "collection": "Always Available",
    "category": "Candle Glass",
    "productionType": "machine",
    "heightOrDiameter": "h82 d90",
    "usableMl": 270,
    "usableOz": 9.1,
    "totalMl": 270,
    "totalOz": 9.1,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 1560,
    "priceEur": 0.52,
    "priceUsd": 0.6032,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/70078.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:70053",
    "sku": "70053",
    "baseIndex": "70053",
    "name": "Cylinder",
    "collection": "Always Available",
    "category": "Candle Glass",
    "productionType": "machine",
    "heightOrDiameter": "h83 d74",
    "usableMl": 240,
    "usableOz": 8.1,
    "totalMl": 240,
    "totalOz": 8.1,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 2232,
    "priceEur": 0.41,
    "priceUsd": 0.4755999999999999,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/70053.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:35532",
    "sku": "35532",
    "baseIndex": "35532",
    "name": "Cylinder",
    "collection": "Always Available",
    "category": "Flora",
    "productionType": "machine",
    "heightOrDiameter": "h100 d100",
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 1040,
    "priceEur": 0.65,
    "priceUsd": 0.754,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/35532.jpg",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:35543",
    "sku": "35543",
    "baseIndex": "35543",
    "name": "Cylinder",
    "collection": "Always Available",
    "category": "Flora",
    "productionType": "machine",
    "heightOrDiameter": "h150 d100",
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 728,
    "priceEur": 1.08,
    "priceUsd": 1.2528,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/35543.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:35840",
    "sku": "35840",
    "baseIndex": "35840",
    "name": "Vase Jar",
    "collection": "Always Available",
    "category": "Flora",
    "productionType": "machine",
    "heightOrDiameter": "h295 d152",
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 105,
    "priceEur": 3.29,
    "priceUsd": 3.8164,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/35840.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:35940",
    "sku": "35940",
    "baseIndex": "35940",
    "name": "Cylinder",
    "collection": "Always Available",
    "category": "Flora",
    "productionType": "machine",
    "heightOrDiameter": "h290 d158",
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 108,
    "priceEur": 3.39,
    "priceUsd": 3.9324,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/35940.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:35588",
    "sku": "35588",
    "baseIndex": "35588",
    "name": "Cylinder",
    "collection": "Always Available",
    "category": "Flora",
    "productionType": "machine",
    "heightOrDiameter": "h295 d100",
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 231,
    "priceEur": 2.09,
    "priceUsd": 2.4244,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/35588.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:35096",
    "sku": "35096",
    "baseIndex": "35096",
    "name": "Cylinder",
    "collection": "Always Available",
    "category": "Flora",
    "productionType": "machine",
    "heightOrDiameter": "h190 d190",
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 120,
    "priceEur": 2.29,
    "priceUsd": 2.6563999999999997,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/35096.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:35162",
    "sku": "35162",
    "baseIndex": "35162",
    "name": "Vase",
    "collection": "Always Available",
    "category": "Flora",
    "productionType": "machine",
    "heightOrDiameter": "h200 d110",
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 240,
    "priceEur": 1.69,
    "priceUsd": 1.9603999999999997,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/35162.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:35445",
    "sku": "35445",
    "baseIndex": "35445",
    "name": "Vase",
    "collection": "Always Available",
    "category": "Flora",
    "productionType": "machine",
    "heightOrDiameter": "h180 d110",
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 378,
    "priceEur": 1.1,
    "priceUsd": 1.276,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/35445.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:35502",
    "sku": "35502",
    "baseIndex": "35502",
    "name": "Vase",
    "collection": "Always Available",
    "category": "Flora",
    "productionType": "machine",
    "heightOrDiameter": "h198 d120",
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 200,
    "priceEur": 1.7,
    "priceUsd": 1.9719999999999998,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/35502.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:35503",
    "sku": "35503",
    "baseIndex": "35503",
    "name": "Vase",
    "collection": "Always Available",
    "category": "Flora",
    "productionType": "machine",
    "heightOrDiameter": "h198 d120",
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 160,
    "priceEur": 1.67,
    "priceUsd": 1.9371999999999998,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/35503.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:35722",
    "sku": "35722",
    "baseIndex": "35722",
    "name": "Jar",
    "collection": "Always Available",
    "category": "Flora",
    "productionType": "machine",
    "heightOrDiameter": "h150 d150",
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 315,
    "priceEur": 1.66,
    "priceUsd": 1.9255999999999998,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/35722.jpg",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:35583",
    "sku": "35583",
    "baseIndex": "35583",
    "name": "Cylinder",
    "collection": "Always Available",
    "category": "Flora",
    "productionType": "machine",
    "heightOrDiameter": "h200 d100",
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 520,
    "priceEur": 1.15,
    "priceUsd": 1.3339999999999999,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/35583.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:35685",
    "sku": "35685",
    "baseIndex": "35685",
    "name": "Jar",
    "collection": "Always Available",
    "category": "Flora",
    "productionType": "machine",
    "heightOrDiameter": "h200 d80",
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 475,
    "priceEur": 1.2,
    "priceUsd": 1.392,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/35685.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:35446",
    "sku": "35446",
    "baseIndex": "35446",
    "name": "Vase",
    "collection": "Always Available",
    "category": "Flora",
    "productionType": "machine",
    "heightOrDiameter": "h180 d109",
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 324,
    "priceEur": 1.09,
    "priceUsd": 1.2644,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/35446.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:35533",
    "sku": "35533",
    "baseIndex": "35533",
    "name": "Jar",
    "collection": "Always Available",
    "category": "Flora",
    "productionType": "machine",
    "heightOrDiameter": "h100 d100",
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "pcsPerPallet": 1040,
    "priceEur": 0.65,
    "priceUsd": 0.754,
    "stockIntl": 10000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/35533.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:70437",
    "sku": "70437",
    "baseIndex": "70437",
    "name": "Whisky Glass",
    "collection": "Stock",
    "category": "HoReCa",
    "productionType": "machine",
    "heightOrDiameter": "h90 d90",
    "usableMl": 300,
    "usableOz": 10.1,
    "totalMl": 300,
    "totalOz": 10.1,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "priceEur": 0.35,
    "priceUsd": 0.40599999999999997,
    "stockIntl": 3826,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/70437.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:72076",
    "sku": "72076",
    "baseIndex": "72076",
    "name": "Drinking Glass",
    "collection": "Stock",
    "category": "HoReCa",
    "productionType": "machine",
    "heightOrDiameter": "h100 d70",
    "usableMl": 150,
    "usableOz": 5,
    "totalMl": 150,
    "totalOz": 5,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "priceEur": 0.35,
    "priceUsd": 0.40599999999999997,
    "stockIntl": 20767,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/72076.jpg",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:80904",
    "sku": "80904",
    "baseIndex": "80904",
    "name": "Bootle",
    "collection": "Stock",
    "category": "HoReCa",
    "productionType": "machine",
    "heightOrDiameter": "h229 d82",
    "usableMl": 700,
    "usableOz": 23.6,
    "totalMl": 700,
    "totalOz": 23.6,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "priceEur": 0.55,
    "priceUsd": 0.638,
    "stockIntl": 22690,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/80904.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:70807",
    "sku": "70807",
    "baseIndex": "70807",
    "name": "Drinking Glass",
    "collection": "Stock",
    "category": "HoReCa",
    "productionType": "machine",
    "heightOrDiameter": "h132 d72",
    "usableMl": 300,
    "usableOz": 10.1,
    "totalMl": 300,
    "totalOz": 10.1,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "priceEur": 0.42,
    "priceUsd": 0.48719999999999997,
    "stockIntl": 2145,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/70807.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:70034",
    "sku": "70034",
    "baseIndex": "70034",
    "name": "Drinking Glass",
    "collection": "Stock",
    "category": "HoReCa",
    "productionType": "machine",
    "heightOrDiameter": "h100 d72",
    "usableMl": 200,
    "usableOz": 6.7,
    "totalMl": 200,
    "totalOz": 6.7,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "priceEur": 0.35,
    "priceUsd": 0.40599999999999997,
    "stockIntl": 15463,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/70034.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:72071",
    "sku": "72071",
    "baseIndex": "72071",
    "name": "Drinking Glass",
    "collection": "Stock",
    "category": "HoReCa",
    "productionType": "machine",
    "heightOrDiameter": "h144 d84",
    "usableMl": 415,
    "usableOz": 14,
    "totalMl": 415,
    "totalOz": 14,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "priceEur": 0.42,
    "priceUsd": 0.48719999999999997,
    "stockIntl": 2088,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/72071.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:38021",
    "sku": "38021",
    "baseIndex": "38021",
    "name": "Beer Glass",
    "collection": "Stock",
    "category": "HoReCa",
    "productionType": "machine",
    "heightOrDiameter": "h254 d75",
    "usableMl": 500,
    "usableOz": 16.9,
    "totalMl": 500,
    "totalOz": 16.9,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "priceEur": 0.58,
    "priceUsd": 0.6728,
    "stockIntl": 24144,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/38021.jpg",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:74414Z",
    "sku": "74414Z",
    "baseIndex": "74414Z",
    "name": "Jug",
    "collection": "Stock",
    "category": "HoReCa",
    "productionType": "machine",
    "heightOrDiameter": "h190 d190",
    "usableMl": 1200,
    "usableOz": 40.5,
    "totalMl": 1200,
    "totalOz": 40.5,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "priceEur": 1.17,
    "priceUsd": 1.3571999999999997,
    "stockIntl": 1124,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/74414Z.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:41364",
    "sku": "41364",
    "baseIndex": "41364",
    "name": "Bowl",
    "collection": "Stock",
    "category": "HoReCa",
    "productionType": "machine",
    "heightOrDiameter": "h79 d181",
    "usableMl": 1100,
    "usableOz": 37.1,
    "totalMl": 1100,
    "totalOz": 37.1,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "priceEur": 0.68,
    "priceUsd": 0.7888000000000001,
    "stockIntl": 1002,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/41364.jpg",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:72074mix",
    "sku": "72074mix",
    "baseIndex": "72074mix",
    "name": "Drinking Glass",
    "collection": "Stock",
    "category": "HoReCa",
    "productionType": "machine",
    "heightOrDiameter": "h144 d84",
    "usableMl": 417,
    "usableOz": 14.1,
    "totalMl": 417,
    "totalOz": 14.1,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "priceEur": 0.42,
    "priceUsd": 0.48719999999999997,
    "stockIntl": 1140,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/72074mix.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:74414r",
    "sku": "74414r",
    "baseIndex": "74414r",
    "name": "Jug",
    "collection": "Stock",
    "category": "HoReCa",
    "productionType": "machine",
    "heightOrDiameter": "h190 d190",
    "usableMl": 1200,
    "usableOz": 40.5,
    "totalMl": 1200,
    "totalOz": 40.5,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "priceEur": 1.17,
    "priceUsd": 1.3571999999999997,
    "stockIntl": 1314,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/74414r.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:70427n",
    "sku": "70427n",
    "baseIndex": "70427n",
    "name": "Whisky Glass",
    "collection": "Stock",
    "category": "HoReCa",
    "productionType": "machine",
    "heightOrDiameter": "h95 d85",
    "usableMl": 329,
    "usableOz": 11.1,
    "totalMl": 329,
    "totalOz": 11.1,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "priceEur": 0.35,
    "priceUsd": 0.40599999999999997,
    "stockIntl": 864,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/70427n.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:41303",
    "sku": "41303",
    "baseIndex": "41303",
    "name": "Bowl",
    "collection": "Stock",
    "category": "HoReCa",
    "productionType": "machine",
    "heightOrDiameter": "h72 d130",
    "usableMl": 450,
    "usableOz": 15.2,
    "totalMl": 450,
    "totalOz": 15.2,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "priceEur": 0.37,
    "priceUsd": 0.42919999999999997,
    "stockIntl": 13550,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/41303.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:71124",
    "sku": "71124",
    "baseIndex": "71124",
    "name": "Drinking Glass",
    "collection": "Stock",
    "category": "HoReCa",
    "productionType": "machine",
    "heightOrDiameter": "h132 d80",
    "usableMl": 280,
    "usableOz": 9.4,
    "totalMl": 280,
    "totalOz": 9.4,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "priceEur": 0.42,
    "priceUsd": 0.48719999999999997,
    "stockIntl": 10106,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/71124.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:74030",
    "sku": "74030",
    "baseIndex": "74030",
    "name": "Ice Cream Cup",
    "collection": "Stock",
    "category": "HoReCa",
    "productionType": "machine",
    "heightOrDiameter": "h100 d100",
    "usableMl": 180,
    "usableOz": 6,
    "totalMl": 180,
    "totalOz": 6,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "priceEur": 0.35,
    "priceUsd": 0.40599999999999997,
    "stockIntl": 1890,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/74030.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:70120or",
    "sku": "70120or",
    "baseIndex": "70120or",
    "name": "Drinking Glass",
    "collection": "Stock",
    "category": "HoReCa",
    "productionType": "machine",
    "heightOrDiameter": "h110 d80",
    "usableMl": 300,
    "usableOz": 10.1,
    "totalMl": 300,
    "totalOz": 10.1,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "priceEur": 0.42,
    "priceUsd": 0.48719999999999997,
    "stockIntl": 20150,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/70120or.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:70120og",
    "sku": "70120og",
    "baseIndex": "70120og",
    "name": "Drinking Glass",
    "collection": "Stock",
    "category": "HoReCa",
    "productionType": "machine",
    "heightOrDiameter": "h110 d80",
    "usableMl": 300,
    "usableOz": 10.1,
    "totalMl": 300,
    "totalOz": 10.1,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "priceEur": 0.42,
    "priceUsd": 0.48719999999999997,
    "stockIntl": 16319,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/70120og.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:74229",
    "sku": "74229",
    "baseIndex": "74229",
    "name": "Beer Glass",
    "collection": "Stock",
    "category": "HoReCa",
    "productionType": "machine",
    "heightOrDiameter": "h155 d106",
    "usableMl": 300,
    "usableOz": 10.1,
    "totalMl": 300,
    "totalOz": 10.1,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "priceEur": 0.58,
    "priceUsd": 0.6728,
    "stockIntl": 2592,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/74229.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:74224",
    "sku": "74224",
    "baseIndex": "74224",
    "name": "Beer Glass",
    "collection": "Stock",
    "category": "HoReCa",
    "productionType": "machine",
    "heightOrDiameter": "h170 d120",
    "usableMl": 400,
    "usableOz": 13.5,
    "totalMl": 400,
    "totalOz": 13.5,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "priceEur": 0.82,
    "priceUsd": 0.9511999999999998,
    "stockIntl": 5184,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/74224.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:74250",
    "sku": "74250",
    "baseIndex": "74250",
    "name": "Drinking Glass",
    "collection": "Stock",
    "category": "HoReCa",
    "productionType": "machine",
    "heightOrDiameter": "h130 d120",
    "usableMl": 370,
    "usableOz": 12.5,
    "totalMl": 370,
    "totalOz": 12.5,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "priceEur": 0.47,
    "priceUsd": 0.5451999999999999,
    "stockIntl": 6912,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/74250.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:74299",
    "sku": "74299",
    "baseIndex": "74299",
    "name": "Beer Glass",
    "collection": "Stock",
    "category": "HoReCa",
    "productionType": "machine",
    "heightOrDiameter": "h160 d93",
    "usableMl": 350,
    "usableOz": 11.8,
    "totalMl": 350,
    "totalOz": 11.8,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "priceEur": 0.58,
    "priceUsd": 0.6728,
    "stockIntl": 2244,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/74299.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:70641",
    "sku": "70641",
    "baseIndex": "70641",
    "name": "Drinking Glass",
    "collection": "Stock",
    "category": "HoReCa",
    "productionType": "machine",
    "heightOrDiameter": "h90 d73",
    "usableMl": 230,
    "usableOz": 7.7,
    "totalMl": 230,
    "totalOz": 7.7,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "priceEur": 0.23,
    "priceUsd": 0.2668,
    "stockIntl": 21054,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/70641.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:38002",
    "sku": "38002",
    "baseIndex": "38002",
    "name": "Drinking Glass",
    "collection": "Stock",
    "category": "HoReCa",
    "productionType": "machine",
    "heightOrDiameter": "h135 d62",
    "usableMl": 250,
    "usableOz": 8.4,
    "totalMl": 250,
    "totalOz": 8.4,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "priceEur": 0.23,
    "priceUsd": 0.2668,
    "stockIntl": 9008,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/38002.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:70120",
    "sku": "70120",
    "baseIndex": "70120",
    "name": "Cube",
    "collection": "Stock",
    "category": "Candle Glass",
    "productionType": "machine",
    "heightOrDiameter": "h80 d80",
    "usableMl": 298,
    "usableOz": 10,
    "totalMl": 298,
    "totalOz": 10,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "priceEur": 0.43,
    "priceUsd": 0.49879999999999997,
    "stockIntl": 27643,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/70120.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:70069",
    "sku": "70069",
    "baseIndex": "70069",
    "name": "Candle Container",
    "collection": "Stock",
    "category": "Candle Glass",
    "productionType": "machine",
    "heightOrDiameter": "h50 d61",
    "usableMl": 60,
    "usableOz": 2,
    "totalMl": 60,
    "totalOz": 2,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "priceEur": 0.14,
    "priceUsd": 0.16240000000000002,
    "stockIntl": 2496,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/70069.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:70018",
    "sku": "70018",
    "baseIndex": "70018",
    "name": "Candle Container",
    "collection": "Stock",
    "category": "Candle Glass",
    "productionType": "machine",
    "heightOrDiameter": "h78 d105",
    "usableMl": 350,
    "usableOz": 11.8,
    "totalMl": 350,
    "totalOz": 11.8,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "priceEur": 0.45,
    "priceUsd": 0.522,
    "stockIntl": 19860,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/70018.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:70860",
    "sku": "70860",
    "baseIndex": "70860",
    "name": "Candle Container",
    "collection": "Stock",
    "category": "Candle Glass",
    "productionType": "machine",
    "heightOrDiameter": "h65 d48",
    "usableMl": 100,
    "usableOz": 3.3,
    "totalMl": 100,
    "totalOz": 3.3,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "priceEur": 0.2,
    "priceUsd": 0.23199999999999998,
    "stockIntl": 850,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/70860.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:80020",
    "sku": "80020",
    "baseIndex": "80020",
    "name": "Candle Container",
    "collection": "Stock",
    "category": "Candle Glass",
    "productionType": "machine",
    "heightOrDiameter": "h70 d74",
    "usableMl": 250,
    "usableOz": 8.4,
    "totalMl": 250,
    "totalOz": 8.4,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "priceEur": 0.16,
    "priceUsd": 0.1856,
    "stockIntl": 1454,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/80020.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:38056",
    "sku": "38056",
    "baseIndex": "38056",
    "name": "Candle Container",
    "collection": "Stock",
    "category": "Candle Glass",
    "productionType": "machine",
    "heightOrDiameter": "h105 d81",
    "usableMl": 350,
    "usableOz": 11.8,
    "totalMl": 350,
    "totalOz": 11.8,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "priceEur": 0.5,
    "priceUsd": 0.58,
    "stockIntl": 63612,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/38056.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:70530",
    "sku": "70530",
    "baseIndex": "70530",
    "name": "Candle Container",
    "collection": "Stock",
    "category": "Candle Glass",
    "productionType": "machine",
    "heightOrDiameter": "h135 d126",
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "priceEur": 0.94,
    "priceUsd": 1.0903999999999998,
    "stockIntl": 3660,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/70530.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:38402cz",
    "sku": "38402cz",
    "baseIndex": "38402cz",
    "name": "Candle Container",
    "collection": "Stock",
    "category": "Candle Glass",
    "productionType": "machine",
    "heightOrDiameter": "h88 d93",
    "usableMl": 380,
    "usableOz": 12.8,
    "totalMl": 380,
    "totalOz": 12.8,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "priceEur": 0.35,
    "priceUsd": 0.40599999999999997,
    "stockIntl": 26020,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/38402cz.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:38059",
    "sku": "38059",
    "baseIndex": "38059",
    "name": "Candle Container",
    "collection": "Stock",
    "category": "Candle Glass",
    "productionType": "machine",
    "heightOrDiameter": "h105 d81",
    "usableMl": 350,
    "usableOz": 11.8,
    "totalMl": 350,
    "totalOz": 11.8,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "priceEur": 0.7,
    "priceUsd": 0.8119999999999999,
    "stockIntl": 10208,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/38059.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:70022",
    "sku": "70022",
    "baseIndex": "70022",
    "name": "Candle Container",
    "collection": "Stock",
    "category": "Candle Glass",
    "productionType": "machine",
    "heightOrDiameter": "h76 d75",
    "usableMl": 209,
    "usableOz": 7.1,
    "totalMl": 209,
    "totalOz": 7.1,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "priceEur": 0.25,
    "priceUsd": 0.29,
    "stockIntl": 2428,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/70022.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:70070",
    "sku": "70070",
    "baseIndex": "70070",
    "name": "Candle Container",
    "collection": "Stock",
    "category": "Candle Glass",
    "productionType": "machine",
    "heightOrDiameter": "h73 d76",
    "usableMl": 160,
    "usableOz": 5.4,
    "totalMl": 160,
    "totalOz": 5.4,
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "priceEur": 0.17,
    "priceUsd": 0.19720000000000001,
    "stockIntl": 3780,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/70070.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:10756b",
    "sku": "10756b",
    "baseIndex": "10756b",
    "name": "Vase",
    "collection": "Stock",
    "category": "Flora",
    "productionType": "machine",
    "heightOrDiameter": "h193 d150",
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "priceEur": 0.94,
    "priceUsd": 1.0903999999999998,
    "stockIntl": 1777,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/10756b.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:35581",
    "sku": "35581",
    "baseIndex": "35581",
    "name": "Vase",
    "collection": "Stock",
    "category": "Flora",
    "productionType": "machine",
    "heightOrDiameter": "h200 d150",
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "priceEur": 1.28,
    "priceUsd": 1.4848,
    "stockIntl": 5931,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/35581.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:35090",
    "sku": "35090",
    "baseIndex": "35090",
    "name": "Vase",
    "collection": "Stock",
    "category": "Flora",
    "productionType": "machine",
    "heightOrDiameter": "h245 d140",
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "priceEur": 1.28,
    "priceUsd": 1.4848,
    "stockIntl": 3334,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/35090.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:35582",
    "sku": "35582",
    "baseIndex": "35582",
    "name": "Vase",
    "collection": "Stock",
    "category": "Flora",
    "productionType": "machine",
    "heightOrDiameter": "h200 d115",
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "priceEur": 1.29,
    "priceUsd": 1.4964,
    "stockIntl": 3916,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/35582.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:35012",
    "sku": "35012",
    "baseIndex": "35012",
    "name": "Vase",
    "collection": "Stock",
    "category": "Flora",
    "productionType": "machine",
    "heightOrDiameter": "h170 d119",
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "priceEur": 0.94,
    "priceUsd": 1.0903999999999998,
    "stockIntl": 2359,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/35012.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:35108",
    "sku": "35108",
    "baseIndex": "35108",
    "name": "Vase",
    "collection": "Stock",
    "category": "Flora",
    "productionType": "machine",
    "heightOrDiameter": "h155 d121",
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "priceEur": 2.11,
    "priceUsd": 2.4475999999999996,
    "stockIntl": 8021,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/35108.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:35490",
    "sku": "35490",
    "baseIndex": "35490",
    "name": "Vase",
    "collection": "Stock",
    "category": "Flora",
    "productionType": "machine",
    "heightOrDiameter": "h200 d135",
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "priceEur": 1.28,
    "priceUsd": 1.4848,
    "stockIntl": 970,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/35490.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:35949",
    "sku": "35949",
    "baseIndex": "35949",
    "name": "Vase",
    "collection": "Stock",
    "category": "Flora",
    "productionType": "machine",
    "heightOrDiameter": "h240 d188",
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "priceEur": 1.76,
    "priceUsd": 2.0416,
    "stockIntl": 2304,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/35949.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:35500",
    "sku": "35500",
    "baseIndex": "35500",
    "name": "Vase",
    "collection": "Stock",
    "category": "Flora",
    "productionType": "machine",
    "heightOrDiameter": "h200 d135",
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "priceEur": 1.07,
    "priceUsd": 1.2412,
    "stockIntl": 4400,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/35500.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:35079",
    "sku": "35079",
    "baseIndex": "35079",
    "name": "Vase",
    "collection": "Stock",
    "category": "Flora",
    "productionType": "machine",
    "heightOrDiameter": "h150 d120",
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "priceEur": 1.07,
    "priceUsd": 1.2412,
    "stockIntl": 4754,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/35079.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:35606",
    "sku": "35606",
    "baseIndex": "35606",
    "name": "Vase",
    "collection": "Stock",
    "category": "Flora",
    "productionType": "machine",
    "heightOrDiameter": "h240 d100",
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "priceEur": 1.29,
    "priceUsd": 1.4964,
    "stockIntl": 2080,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/35606.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:35075",
    "sku": "35075",
    "baseIndex": "35075",
    "name": "Vase",
    "collection": "Stock",
    "category": "Flora",
    "productionType": "machine",
    "heightOrDiameter": "h200 d140",
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "priceEur": 1.05,
    "priceUsd": 1.218,
    "stockIntl": 1200,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/35075.png",
    "createdAt": 0
  },
  {
    "id": "sup-solbika:35521",
    "sku": "35521",
    "baseIndex": "35521",
    "name": "Vase",
    "collection": "Stock",
    "category": "Flora",
    "productionType": "machine",
    "heightOrDiameter": "h195 d142",
    "pcsPerBox": 6,
    "pcsPerCarton": 6,
    "priceEur": 1.07,
    "priceUsd": 1.2412,
    "stockIntl": 2000,
    "supplier": "Solbika",
    "supplierId": "sup-solbika",
    "status": "approved",
    "imageKey": "/images/solbika/35521.png",
    "createdAt": 0
  }
];
